### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/gno.land-r-manfred#1]
# Contracts

* [ ] personal blog
* [ ] personal profile
* [ ] personal ACL system
* [ ] personal meta wallets, i.e., vault

# Features

* [ ] setup script to publish/update/version
* [ ] generate clients
* [ ] setup CI
